title: MAJID JANGANI
description: Market Risk Analystics for Equity Portfolio 
show_downloads: true
theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
plugins:
  - jekyll-remote-theme
permalink: /:title/
baseurl: "/Market-Risk-Analytics"
